# هذه هي منصات نموذج التمويل المدعومة

جيثب.: # استبدل بأسماء مستخدمين تدعم رعاة GitHub على سبيل المثال، [المستخدم1، المستخدم2]
باتريون.: # استبدال مع اسم مستخدم Patreon واحد
فتح_الجماعية.: # استبدال مع اسم مستخدم واحد مفتوح جماعي
كو_في.: # استبدال مع اسم مستخدم Ko-fi واحد
رفع المد والجزر.: # استبدلها بمنصة Tidelift واحدة - الاسم / الحزمة - الاسم على سبيل المثال، npm / babel
المجتمع_بريدج: # استبدلها باسم مشروع جسر مجتمعي واحد على سبيل المثال، مسبك سحابي
ليبراباي؟: # استبدال مع اسم مستخدم Liberapay واحد
مطاردة القضايا.: # استبدال مع اسم مستخدم IssueHunt واحد
lfx_التمويل الجماعي: # استبدلها باسم مشروع LFX Crowdfunding واحد على سبيل المثال، مسبك السحابة
القطبية.: # استبدال مع اسم مستخدم قطبي واحد
شراء_me_a_قهوة: # استبدال مع اسم مستخدم واحد شراء لي القهوة
شكرا_ديف.: # استبدال مع اسم مستخدم واحد thanks.dev
العرف.: # استبدل ما يصل إلى 4 عناوين URL مخصصة للرعاية على سبيل المثال، ['link1'، 'link2']
